version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./.ssl:/etc/nginx/ssl:ro
    networks:
      - frontend_network

  recipes_api:
    image: recipes_app
    networks:
      - recipes_network
      - frontend_network
      - infrastructure_network

  rss_api:
    image: rss_producer
    networks:
      - rss_network
      - frontend_network
      - infrastructure_network

  rss_worker:
    image: rss_worker
    networks:
      - rss_network
      - infrastructure_network

networks:
  frontend_network:
  recipes_network:
  rss_network:
  infrastructure_network:
    name: infrastructure_network
    external: true
